travis:
  secure:
    BINSTAR_TOKEN: DG1w0OH5Wh5KNKt0mRrjZ4mULnQedamDt79mjXbJPj0X4m6cel9LUFmpoub3w4NlKf6dPbkMW94d6wRrGCvLx06ctzIKPE7fP2qoeoKBaMVY/vQ4OI/iX/pdoMNXXHAzP8KzDLMzikD9c7/W/d3H/iHN16Okn/F7VdLnFByPCurA3Eu0N4G56Y/q0vAceTo31fgV/p0U3FeUWD2zQoFX99Jj2iTWpzwP6vxzAxd6vekMiZVzs1BIaWNXjFEkWPafq9x3XOHFtsbkzq0rkJ2DC1IX3amJwU/pa0o/SyZpU3ZOuFRkiD7bf/uNpq9WH50xb5yKbaDLsgDRljNseu8QivyMkcU0enpk1XS9y9H3+/TG/UZcmjpDNi7cn5OanRgF7D4rqs+Kfpz+0qDLO1m+aIIDU1qr/UyYRF14IwyylHL5OxmphXI9E1qjnx8kTbiZBUedMD6CipjbqmBXEVbdRWUgzzBiFE1TFxSjSLS5gyTzbpuNkX+oofwfD30ZdoTeTSagrXutTn3Z9KWa0WqxZ6cdePZY7wKN1R2hFlLwDZWPGZiIxWHphO8VVDmGfUlOVkWKKoyWCL4AU0umxB2o5Nm8em12dmgYyupvNA74pZg43NjmkU5oTfQz0cwdzZlAAtaGVylA7XRwyjMxahtO12ZRYxzXLPAvybbkomwg8PM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
