travis:
  secure:
    BINSTAR_TOKEN: NqGdPiYtKiIm4EBOLlmptkmZH2n0la1IR4C1iI+05k2OoSTECsdXqrmEOS24MF/CUcxmchto7AEfLRL6fWiKrKF+OLJ8yeQiR1F2LRrVooyEmmMSywK4u/Nrz9WwSCMyPpCyXYU+iHV3LpsnropwL7DAvoLEne0YSgzMIxPKYCa4KSeS0Z7IgK/Om8aFlw8ntEhVH3d2hTJd1shjqo72y+JeCDMNJu4/SZ7GLTmv5ikwlQr4ARNBZo9iwAP9VIE8k2PLdkmllYf4tyEhkRGQwoHFEGt55ySbtBySZpGt8l+3vn2nofhALcfEBW/0h9L8qyUzWdDy22MV6jLuUxf+33NAxCH3QFuZxyMcMsiDTL7TmcgtbOCrzLWOyZ2Zupmnov+ddas0OtW5PLApMXbwbxs2iXJC7BU9tBbKQFeQoNC9QRnMQXIREloF+RcWfF+R2qA5LzjObNKMAkr+PGh7fXw2bPzqSFFp2sGDPx18o/1Tzl7hM2y2JSA/6J779HjVV+NyqrKc4W684kaW2PTld0JmKyWPnEVHsFGRaxX6t4lbER4A/xSXoOA/aFv4cP8u48AOnmUk2Ofe9Vb0/M8ymUgGAwvgBvwNk3wAuABw/3bhG4VuKDbryR2z4f4IL2nAQxt1T+30nbPCQbrN1pgSVBvfCm9jiH4nGPlXveo2mAs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
